-- Create USERS table with auto generated "id" column
-- Note: Oracle will auto create a sequence for "id" genration
CREATE TABLE USERS
(
    id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    firstName VARCHAR2(100),
    lastName  VARCHAR2(100),
    email     VARCHAR2(255)
);

-- Insert fake data into USERS table using following query
INSERT INTO USERS (firstName, lastName, email) VALUES ('John', 'Doe', 'john.doe@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Jane', 'Smith', 'jane.smith@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Alice', 'Johnson', 'alice.johnson@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Bob', 'Williams', 'bob.williams@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Emma', 'Brown', 'emma.brown@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Charlie', 'Jones', 'charlie.jones@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Ella', 'Davis', 'ella.davis@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Frank', 'Martinez', 'frank.martinez@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Grace', 'Hernandez', 'grace.hernandez@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Henry', 'Young', 'henry.young@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Isabella', 'Garcia', 'isabella.garcia@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Jack', 'Lee', 'jack.lee@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Katherine', 'Lopez', 'katherine.lopez@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Liam', 'Hall', 'liam.hall@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Madison', 'Cook', 'madison.cook@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Nathan', 'Perez', 'nathan.perez@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Olivia', 'Scott', 'olivia.scott@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Oscar', 'Green', 'oscar.green@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Penelope', 'Adams', 'penelope.adams@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Quinn', 'Campbell', 'quinn.campbell@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Ryan', 'Russell', 'ryan.russell@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Sophia', 'Carter', 'sophia.carter@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Samuel', 'Rivera', 'samuel.rivera@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Taylor', 'Torres', 'taylor.torres@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Victoria', 'Nguyen', 'victoria.nguyen@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('William', 'Thompson', 'william.thompson@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Zoe', 'Wright', 'zoe.wright@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Ava', 'Mitchell', 'ava.mitchell@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Benjamin', 'Roberts', 'benjamin.roberts@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Charlotte', 'Gomez', 'charlotte.gomez@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Daniel', 'Kelly', 'daniel.kelly@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Emily', 'Howard', 'emily.howard@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Ethan', 'Nelson', 'ethan.nelson@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Gabriel', 'Baker', 'gabriel.baker@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Hannah', 'Evans', 'hannah.evans@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Jacob', 'Rodriguez', 'jacob.rodriguez@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Lily', 'Parker', 'lily.parker@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Matthew', 'Morales', 'matthew.morales@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Mia', 'Cooper', 'mia.cooper@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Noah', 'Richardson', 'noah.richardson@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Sophie', 'Gray', 'sophie.gray@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Tyler', 'Murphy', 'tyler.murphy@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Elizabeth', 'Torres', 'elizabeth.torres@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Elijah', 'Peterson', 'elijah.peterson@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Avery', 'Reed', 'avery.reed@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Grace', 'Barnes', 'grace.barnes@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Jeff', 'Bezos', 'jeff.bezos@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Bill', 'Gates', 'bill.gates@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Mark', 'Anderson', 'mark.anderson@example.com');
INSERT INTO USERS (firstName, lastName, email) VALUES ('Kelly', 'Anderson', 'kelly.anderson@example.com');


-- Get all records form the table using following query
SELECT * FROM USERS;


purge recyclebin; -- We can delete system generated sequence with this command